name: bump_version

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: |
          # ваш install
      - name: Run tests
        run: |
          # ваши тесты

  bump-version:
    name: Bump Version
    needs: build-and-test
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.title, 'feature') || contains(github.event.pull_request.title, 'hotfix') }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0    

      - name: Bump version
        id: bump
        run: |
          TYPE=$(echo "${{ github.event.pull_request.title }}" | grep -oE 'feature|hotfix')
          ./bump-version.sh "$TYPE"

      - name: Commit & Push new version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          OLD=${{ steps.bump.outputs.old }}
          NEW=${{ steps.bump.outputs.new }}
          TYPE=${{ steps.bump.outputs.type }}
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add version
          git commit -m "[$NEW] <- [$OLD] $TYPE up"
          git push origin HEAD:${{ github.head_ref }}

      - name: Add PR label with version
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ steps.bump.outputs.new }}
