# .github/workflows/changelog.yml
name: Generate Changelog

on:
  workflow_dispatch:

jobs:
  build-changelog:
    name: Формирование changelog.md
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'changelog' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate changelog entry
        run: |
          DATE=$(date -u +"%Y-%m-%d")
          NEW=$(<version)
          BRANCH=${{ github.head_ref }}
          sed -i "1i- [$DATE] **$NEW**: branch ${BRANCH}" changelog.md

      - name: Commit & Push changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add changelog.md
          git commit -m "docs: add changelog entry for version $NEW"
          git push origin HEAD:${{ github.head_ref }}

      - name: Upload changelog as artifact
        uses: actions/upload-artifact@v3
        with:
          name: changelog
          path: changelog.md
