# .github/workflows/prepare-release.yml
name: Prepare Release

on:
  workflow_dispatch:

jobs:
  create-release:
    name: Создать Release в GitHub
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'PROD' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Read version and changelog description
        id: meta
        run: |
          VERSION=$(<version)
          DESCRIPTION=$(head -n 2 changelog.md | sed ':a;N;$!ba;s/\n/\\n/g')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "description=$DESCRIPTION" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.meta.outputs.version }}
          release_name: Release ${{ steps.meta.outputs.version }}
          body: ${{ steps.meta.outputs.description }}
          draft: false
          prerelease: false
