name: Testing application
on:
  workflow_dispatch:

jobs:
  tests:
    name: "Test: ${{ matrix.file }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        file:
          - tests/test_cli.py
          - tests/test_weather.py

    steps:
      - uses: actions/checkout@v4
      - name: Set up venv
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
      - name: Run ${{ matrix.file }}
        run: |
          source .venv/bin/activate
          pytest ${{ matrix.file }}
