name: Testing application
on:
    workflow_dispatch:

jobs:
    build:
        runs-on: self-hosted #SELF HOSTED or ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up venv
              run: |
                  python3 -m venv .venv
                  source .venv/bin/activate
                  pip install -r requirements.txt
        
            - name: Run tests
              run: |
                source .venv/bin/activate
                pytest -n auto